site_name: YASF
site_description: Yet Another Scattering Framework
site_url: https://agbv.github.io/yasf
repo_url: https://github.com/AGBV/YASF

nav:
  - Home: index.md
  - Reference:
      - references/index.md
      - references/particles.md
      - references/initial_field.md
      - references/parameters.md
      - references/solver.md
      - references/numerics.md
      - references/simulation.md
      - references/optics.md
  - Testing:
      - testing/index.md
      #- coverage.md
  - TODO: todo.md

theme:
  name: "material"
  logo: "assets/img/logo_white.svg"
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.integrate
  custom_dir: docs/overrides

plugins:
  - autorefs:
  # - coverage:
  #     page_name: coverage
  #     html_report_dir: coverage-report/htmlcov
  - search:
      lang: en
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths:
            - yasfpy
          options:
            docstring_style: numpy
            docstring_section_style: table
            members_order: source
            merge_init_into_class: true
            separate_signature: false
            show_if_no_docstring: true
            show_source: true
            show_root_full_path: false
            # heading_level: 2

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - css/mkdocstrings.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
