site_name: YASF
site_description: Yet Another Scattering Framework
site_url: https://agbv.github.io/yasf
repo_url: https://github.com/AGBV/YASF

nav:
  - Home: index.md
  - Code Reference: reference/
  # - Reference:
  #     - references/index.md
  #     - references/particles.md
  #     - references/initial_field.md
  #     - references/parameters.md
  #     - references/solver.md
  #     - references/numerics.md
  #     - references/simulation.md
  #     - references/optics.md
  - Testing:
      - testing/index.md
      #- coverage.md
  - TODO: todo.md

theme:
  name: "material"
  logo: "assets/img/logo_white.svg"
  favicon: "assets/img/logo_white.svg"
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.integrate
  custom_dir: docs/overrides

plugins:
  - autorefs:
  # - coverage:
  #     page_name: coverage
  #     html_report_dir: coverage-report/htmlcov
  - search:
      lang: en
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
        - scripts/todo.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths:
            - yasfpy
          hide:
            - instance-attribute
          options:
            # General options: various options that do not fit in the other categories
            show_bases: true
            show_source: true
            # Headings options: options related to headings and the table of contents (or sidebar, depending on the theme used)
            show_root_full_path: false
            # Members options: options related to filtering or ordering members in the generated documentation
            members_order: source
            summary: false
            # Docstrings options: options related to docstrings (parsing and rendering)
            docstring_style: google
            docstring_section_style: table
            merge_init_into_class: true
            show_if_no_docstring: true
            # Signature options: options related to signatures and type annotations
            show_signature: false
            separate_signature: false
            # heading_level: 2

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - css/mkdocstrings.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
