name: Publish docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - ".github/workflows/mkdocs.yml"
      - "!yasfpy/**"
      - "!tests/**"
      #- "!.github/workflows/test-self-hosted-conda.yml"
      #- "!sonar-project.properties"
  # workflow_run:
  #   workflows:
  #     - Unit tests on self-hosted with Conda
  #   types:
  #     - completed

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          lfs: false

      # - name: Download artifact
      #   uses: dawidd6/action-download-artifact@v4
      #   with:
      #     workflow: testing.yml
      #     name: coverage-report

      - name: Install uv
        id: setup-python
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Setup venv for docs & install dependencies
        if: steps.cache-env.outputs.cache-hit != 'true'
        run: |
          uv venv
          uv sync --only-group docs

      - name: Publish
        run: uv run --only-group docs mkdocs gh-deploy --force

      # - name: Deploy docs
      #   uses: mhausenblas/mkdocs-deploy-gh-pages@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     CONFIG_FILE: mkdocs.yml
      #     # EXTRA_PACKAGES: build-base
      #     REQUIREMENTS: ./requirements.txt
